name: bridge_cheat_detector
description: A Flutter app for detecting cheating in bridge card games using YOLO and eye blink detection.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+5
  tflite_flutter: ^0.11.0
  google_fonts: ^4.0.0
  image: ^4.1.3
  path_provider: 2.0.15
  path: ^1.8.3
  provider: ^6.0.5
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  permission_handler: ^11.0.1
  cupertino_icons: ^1.0.6
  tflite_flutter_helper: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/iconapk.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/models/yolov8n_float32.tflite
    - assets/labels.txt
    - assets/icon/iconapk.png
  
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Roboto-Bold.ttf
  #         weight: 700
  #       - asset: fonts/Roboto-Light.ttf
  #         weight: 300